// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJnc1gkCAJSJJJHhQFEtkOF8g4QLjZSA',
    appId: '1:756435804923:web:b034a06e3fec2d07c5865e',
    messagingSenderId: '756435804923',
    projectId: 'shadan-instagram-clone-project',
    authDomain: 'shadan-instagram-clone-project.firebaseapp.com',
    storageBucket: 'shadan-instagram-clone-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX15zzvE8reBSjSJWwmlo4zm-xqLUQ24Q',
    appId: '1:756435804923:android:b138411e1d300f79c5865e',
    messagingSenderId: '756435804923',
    projectId: 'shadan-instagram-clone-project',
    storageBucket: 'shadan-instagram-clone-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkW-S23zxKmnYQXNVLHYaZ6nZQ2ZECajI',
    appId: '1:756435804923:ios:4696fd34752d7c94c5865e',
    messagingSenderId: '756435804923',
    projectId: 'shadan-instagram-clone-project',
    storageBucket: 'shadan-instagram-clone-project.appspot.com',
    iosClientId: '756435804923-esd38fafenf5kqe7joslqqqfe6cnvva4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
